### PR TITLE
Fixed URL Patterns

### PR DESCRIPTION
**Pull request by PotatoDrug**
Currently if we want to access any of the URLs it can start with any random string as long as it ends with one of the URL patterns.  

For example, `example.com/api/login` and `example.com/api/randomstringlogin` both works and gets directed to the same view.

Adding a `^` to the URL patterns fixes that.

### CODE REVIEW

**Comment by szopu** [comment]
Thanks for the contribution. Before merging I would like to reproduce the issue, hopefully today or tomorrow.

**Comment by szopu** [comment]
@PotatoDrug Hi, sorry for the delay. I reproduced the issue. Could you rebase your code w.r.t. current `master` branch?

**Comment by PotatoDrug** [comment]
How do i do that?

**Comment by szopu** [comment]
If you have problem with that, I can cherry-pick your commit and apply it on current master. This way I could preserve the original author of the commit. However, I will need to close this PR. How about that?

**Comment by szopu** [comment]
I cherry-picked the commit with the actual change, so I'm closing this PR. Thanks!

**Pull request closed without merging**
